# 错误处理
在请求对象`Request`和响应对象`Response`中，都有一个`Error`属性，用于存储错误信息。在链式调用过程中，如果发生错误，最后发生的错误将会被写入`Error`属性中，可以通过该属性获取错误信息  
并且，当执行`Do()`方法后，请求对象中的`Error`信息将被继承到响应对象中，可以通过响应对象的`Error`属性获取请求对象的错误信息
```go
// 请求对象的错误处理
if err := yuzuhttp.Get("https://example.com/").Error; err != nil {
    panic(err)
}

// 响应对象的错误处理
if err := yuzuhttp.Get("https://example.com/").Do().Error; err != nil {
    panic(err)
}
```

如果在链式方法中执行了响应体的**最终方法**，例如`BodyString()`、`BodyJSON()`等解析的Body的方法，则需要无法再使用`Error`属性，因为最终方法将不会返回响应对象，而是直接返回错误信息，可以直接使用正常的方式来处理错误  
*在执行**最终方法**后，将无法继续拼接链式方法*
```go
var BodyStr string
if err := yuzuhttp.Get("https://example.com/").Do().BodyString(&BodyStr); err != nil {
    panic(err)
}

var BodyJsonData map[string]any
if err := yuzuhttp.Get("https://example.com/").Do().BodyJSON(&BodyJsonData); err != nil {
    panic(err)
}
```